src/Entity/Post.php
<?php

namespace App\Entity;

use App\Repository\PostRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: PostRepository::class)]
class Post
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 255)]
    private $title;

    #[ORM\Column(type: 'string', length: 255)]
    private $content;

    #[ORM\ManyToOne(targetEntity: User::class, inversedBy: 'posts')]
    private $user_fk;

    #[ORM\OneToMany(mappedBy: 'post_fk', targetEntity: Commentary::class)]
    private $commentaries;

    #[ORM\Column(type: 'boolean')]
    private $publish;

    public function __construct()
    {
        $this->commentaries = new ArrayCollection();
    }

    public function __toString() : string
    {
        return $this->getTitle();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getUserFk(): ?User
    {
        return $this->user_fk;
    }

    public function setUserFk(?User $user_fk): self
    {
        $this->user_fk = $user_fk;

        return $this;
    }

    /**
     * @return Collection<int, Commentary>
     */
    public function getCommentaries(): Collection
    {
        return $this->commentaries;
    }

    public function addCommentary(Commentary $commentary): self
    {
        if (!$this->commentaries->contains($commentary)) {
            $this->commentaries[] = $commentary;
            $commentary->setPostFk($this);
        }

        return $this;
    }

    public function removeCommentary(Commentary $commentary): self
    {
        if ($this->commentaries->removeElement($commentary)) {
            // set the owning side to null (unless already changed)
            if ($commentary->getPostFk() === $this) {
                $commentary->setPostFk(null);
            }
        }

        return $this;
    }

    public function getPublish(): ?bool
    {
        return $this->publish;
    }

    public function setPublish(bool $publish): self
    {
        $this->publish = $publish;

        return $this;
    }
}

src/Controller/HomeController.php
<?php

namespace App\Controller;

use App\Entity\Commentary;
use App\Entity\Post;
use App\Form\CommentaryFormType;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class HomeController extends AbstractController
{
    #[Route('/', name: 'Home', methods: ['GET'])]
    public function home(EntityManagerInterface $em) : Response
    {
        $posts = $em->getRepository(Post::class)->findAll();

        return $this->render("./home/home.html.twig", [
            'posts' => $posts
        ]);
    }

    #[Route('/onePost_{id}', name: 'onepost')]
    public function onepost(Post $post, Request $request, EntityManagerInterface $em) : Response
    {
        $commentary = new Commentary();
        $form = $this->createForm(CommentaryFormType::class, $commentary);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $commentary->setUserFk($this->getUser())->setPostFk($post)->setDate(new \DateTime());
            $em->persist($commentary);
            $em->flush();
        }

        return $this->render("./home/post.html.twig", [
            'post' => $post,
            'form' => $form->createView(),
        ]);
    }

    #[Route('/moderator', name: "Moderation", methods: ['GET'])]
    public function moderator() : Response
    {
        return $this->render("./moderator/moderator.html.twig", [
        ]);
    }
}

templates/home/home.html.twig
{% extends "base.html.twig" %}

{% block title %}Home{% endblock %}
{% block body %}
    <div class="row mb-2">
        {% for post in posts %}
            {% if post.publish == "1" %}
                <div class="col-md-6">
                    <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
                        <div class="col p-4 d-flex flex-column position-static">
                            <div>
                                {% trans %}By{% endtrans%}
                                <img class="avatar" alt="Profil Picture" src="https://freesvg.org/img/Placeholder.png">
                                <strong class="d-inline-block mb-2 text-primary">{{ post.userFk }}</strong>
                            </div>
                            <h3 class="mb-0">{{ post.title }}</h3>
                            {# <div class="mb-1 text-muted">Feb 10</div> #}
                            <p class="card-text mb-auto">{{ post.content }}</p>
                            <a class="stretched-link" href="{{ path('onepost', {"id": post.id}) }}">{% trans %}Read More{% endtrans %}</a>
                        </div>
                        <div class="col-auto d-none d-lg-block">
                            <img alt="Image" height="300px" src="https://freesvg.org/img/Placeholder.png">
                        </div>
                    </div>
                </div>
            {% endif %}
        {% endfor %}
    </div>

{% endblock %}

templates/home/post.html.twig
{% extends "base.html.twig" %}

{% block title %}Home{% endblock %}
{% block body %}
    <div class="p-4 p-md-5 mb-4 text-white rounded bg-dark">
        <div class="col-md-6 px-0">
            <h1 class="display-4 fst-italic">{{ post.title }}</h1>
            <p class="lead my-3">{{ post.content }}</p>
            <div>
                By
                <img src="https://freesvg.org/img/Placeholder.png" height="50px" width="50px">
                <strong class="d-inline-block mb-2 text-primary">{{ post.userFk }}</strong>
            </div>
        </div>
    </div>

    {% for commentary in post.commentaries %}
        <div class="p-4 mb-3 bg-light rounded">
            <h4 class="fst-italic">{{ commentary.userFk }}</h4>
            <div>{{ commentary.date|date }}</div>
            <p class="mb-0">{{ commentary.content }}</p>
        </div>
    {% endfor %}

    {% if is_granted("ROLE_USER") %}
        <div class="container-fluid mt-4 w-50">
            <h3>New message</h3>
            {% form_theme form 'bootstrap_5_layout.html.twig' %}
            {{ form(form) }}
        </div>
    {% endif %}

{% endblock %}